export SEISCOMP_ROOT="/home/seiscomp"
export PATH="/home/seiscomp/bin:$PATH"
export LD_LIBRARY_PATH="/home/seiscomp/lib:$LD_LIBRARY_PATH"
export PYTHONPATH="/home/seiscomp/lib/python:$PYTHONPATH"
export MANPATH="/home/seiscomp/share/man:$MANPATH"
source "/home/seiscomp/share/shell-completion/seiscomp.bash"
